In [486]:
import xlrd
# comentarios
#path: direccion de archivo

import os
import pandas as pd
import numpy as np
import array as arr
import altair as alt

pd.set_option("display.max_columns",None)

In [487]:
gastoIES = pd.read_excel("n2017_PY_Gasto_en_Salud_por_Fuente_de_Financiamiento_1993-2017.xlsx")
gastoIES=gastoIES[["Anio","Estado_Abreviado","EstadoPrint","IES_GPTS_porcentaje_PIB","PIBmxn","IES_GPTS_porcentaje_GPT","IES_GPS_PERCAPITA_Total_n2017"]]
gastoIES=gastoIES[gastoIES.Estado_Abreviado != "EUM"].rename(columns={"Estado_Abreviado":"Estado","IES_GPTS_porcentaje_PIB":"PIB","IES_GPTS_porcentaje_GPT":"GPT","IES_GPS_PERCAPITA_Total_n2017":"PERCAPITA"})

In [488]:
periodo = 6
sexenios = [i for i in range(gastoIES.Anio.min(), gastoIES.Anio.max()+periodo, periodo)]
sexenios=[1995,2001,2007,2013,2018]
print(sexenios)

sexeniosCol = pd.cut(gastoIES.Anio, bins=sexenios, precision=0, right=False)
gastoIES.insert(1, "sexenio", sexeniosCol)
gastoIES.head()

[1995, 2001, 2007, 2013, 2018]

,Anio,sexenio,Estado,EstadoPrint,PIB,PIBmxn,GPT,PERCAPITA
1,1995,"[1995, 2001)",AGS,Aguascalientes,2.278928,7.917746e+07,10.647619,1959.069682
2,1995,"[1995, 2001)",BC,Baja California,2.163063,2.294365e+08,22.601979,2317.759096
3,1995,"[1995, 2001)",BCS,Baja California Sur,3.742114,3.864674e+07,21.956918,3609.493866
4,1995,"[1995, 2001)",CAMP,Campeche,1.537610,9.870427e+07,6.582009,2409.419805
5,1995,"[1995, 2001)",COAH,Coahuila,2.400249,2.400484e+08,17.083340,2621.670253

In [489]:
new_labels = ["S1", "S2", "S3", "S4"]
gastoIES["sexenio"] = gastoIES["sexenio"].cat.rename_categories(new_labels)

In [490]:
# gastoIES["PIB"] = (gastoIES["PIB"]/100).apply(lambda x: '{:.2%}'.format(x))

In [491]:
# gastoIES["GPT"] = (gastoIES["GPT"]/100).apply(lambda x: '{:.2%}'.format(x))

In [492]:
gastoIES

,Anio,sexenio,Estado,EstadoPrint,PIB,PIBmxn,GPT,PERCAPITA
1,1995,S1,AGS,Aguascalientes,2.278928,7.917746e+07,10.647619,1959.069682
2,1995,S1,BC,Baja California,2.163063,2.294365e+08,22.601979,2317.759096
3,1995,S1,BCS,Baja California Sur,3.742114,3.864674e+07,21.956918,3609.493866
4,1995,S1,CAMP,Campeche,1.537610,9.870427e+07,6.582009,2409.419805
5,1995,S1,COAH,Coahuila,2.400249,2.400484e+08,17.083340,2621.670253
...,...,...,...,...,...,...,...,...
754,2017,S4,TAMPS,Tamaulipas,3.181874,6.078901e+08,18.173028,5339.333865
755,2017,S4,TLAX,Tlaxcala,4.977256,1.154003e+08,28.274960,4374.314206
756,2017,S4,VER,Veracruz,3.916907,9.402165e+08,17.513495,4510.971605
757,2017,S4,YUC,Yucatán,4.249854,3.004113e+08,22.314929,5875.742148
758,2017,S4,ZAC,Zacatecas,3.747525,1.971711e+08,25.655200,4616.959496

In [493]:
gastoSexenios=gastoIES.sort_values(by=["Estado","Anio"],ascending=True).reset_index()
gastoSexenios

,index,Anio,sexenio,Estado,EstadoPrint,PIB,PIBmxn,GPT,PERCAPITA
0,1,1995,S1,AGS,Aguascalientes,2.278928,7.917746e+07,10.647619,1959.069682
1,34,1996,S1,AGS,Aguascalientes,1.987116,8.690798e+07,10.914541,1838.158261
2,67,1997,S1,AGS,Aguascalientes,2.143517,9.629624e+07,13.529886,2155.873869
3,100,1998,S1,AGS,Aguascalientes,2.319555,1.003836e+08,13.109835,2388.303511
4,133,1999,S1,AGS,Aguascalientes,2.761372,1.073634e+08,15.017065,2989.039477
...,...,...,...,...,...,...,...,...,...
731,626,2013,S4,ZAC,Zacatecas,3.941298,1.694030e+08,21.766645,4307.035375
732,659,2014,S4,ZAC,Zacatecas,3.834181,1.743785e+08,21.374967,4276.775771
733,692,2015,S4,ZAC,Zacatecas,3.856125,1.841990e+08,22.107488,4506.750129
734,725,2016,S4,ZAC,Zacatecas,3.674188,1.918374e+08,21.830197,4437.413443
735,758,2017,S4,ZAC,Zacatecas,3.747525,1.971711e+08,25.655200,4616.959496

In [494]:

gastoIES

,Anio,sexenio,Estado,EstadoPrint,PIB,PIBmxn,GPT,PERCAPITA
1,1995,S1,AGS,Aguascalientes,2.278928,7.917746e+07,10.647619,1959.069682
2,1995,S1,BC,Baja California,2.163063,2.294365e+08,22.601979,2317.759096
3,1995,S1,BCS,Baja California Sur,3.742114,3.864674e+07,21.956918,3609.493866
4,1995,S1,CAMP,Campeche,1.537610,9.870427e+07,6.582009,2409.419805
5,1995,S1,COAH,Coahuila,2.400249,2.400484e+08,17.083340,2621.670253
...,...,...,...,...,...,...,...,...
754,2017,S4,TAMPS,Tamaulipas,3.181874,6.078901e+08,18.173028,5339.333865
755,2017,S4,TLAX,Tlaxcala,4.977256,1.154003e+08,28.274960,4374.314206
756,2017,S4,VER,Veracruz,3.916907,9.402165e+08,17.513495,4510.971605
757,2017,S4,YUC,Yucatán,4.249854,3.004113e+08,22.314929,5875.742148
758,2017,S4,ZAC,Zacatecas,3.747525,1.971711e+08,25.655200,4616.959496

In [495]:
with pd.ExcelWriter("GASTO_CSV.xlsx") as writer:
  gastoIES.to_excel(writer, sheet_name="gasto")

In [496]:
gastoSexenios= gastoIES
arrowSexenios= gastoIES
gastoSexenios

,Anio,sexenio,Estado,EstadoPrint,PIB,PIBmxn,GPT,PERCAPITA
1,1995,S1,AGS,Aguascalientes,2.278928,7.917746e+07,10.647619,1959.069682
2,1995,S1,BC,Baja California,2.163063,2.294365e+08,22.601979,2317.759096
3,1995,S1,BCS,Baja California Sur,3.742114,3.864674e+07,21.956918,3609.493866
4,1995,S1,CAMP,Campeche,1.537610,9.870427e+07,6.582009,2409.419805
5,1995,S1,COAH,Coahuila,2.400249,2.400484e+08,17.083340,2621.670253
...,...,...,...,...,...,...,...,...
754,2017,S4,TAMPS,Tamaulipas,3.181874,6.078901e+08,18.173028,5339.333865
755,2017,S4,TLAX,Tlaxcala,4.977256,1.154003e+08,28.274960,4374.314206
756,2017,S4,VER,Veracruz,3.916907,9.402165e+08,17.513495,4510.971605
757,2017,S4,YUC,Yucatán,4.249854,3.004113e+08,22.314929,5875.742148
758,2017,S4,ZAC,Zacatecas,3.747525,1.971711e+08,25.655200,4616.959496

In [497]:
arrowSexenios.set_index("Estado",inplace=True)

In [498]:

tableArrow=arrowSexenios.pivot_table(index=["Estado"], columns=["sexenio"], values=["PIB","PIBmxn","GPT","PERCAPITA"])
tableArrow

               GPT                                     PERCAPITA               \
sexenio         S1         S2         S3         S4           S1           S2
Estado
AGS      12.666491  20.431667  22.951667  25.119454  2388.982393  3676.830666
BC       18.483327  21.611667  24.318333  24.483202  2434.755124  3200.106259
BCS      18.007826  20.620000  18.488333  17.387763  3958.943348  5409.920503
CAMP      6.018588   7.696667   5.236667   3.313836  2740.754515  4751.925666
CDMX     13.131239  10.718333   9.536667   6.914511  6268.273877  8855.970946
CHIH     20.343685  21.448333  24.680000  23.747775  2453.667441  3478.076760
CHIS      9.543822  15.070000  17.701667  18.481366  1103.833708  1947.593523
COAH     18.311397  23.890000  24.238333  22.689162  2844.199384  3873.968322
COL      10.633101  13.263333  11.938333  11.692702  2792.484812  4476.852641
DGO      15.530610  18.071667  17.010000  17.773256  2162.316808  3688.940104
EDOMEX   19.756355  27.713333  33.976667  30.597387  1180.438203  2024.809886
GRO      12.343186  15.053333  18.260000  18.171448  1280.413029  2302.756644
GTO      17.715124  22.361667  27.053333  25.056440  1264.398089  2283.141225
HGO      10.154013  14.185000  14.001667  15.613617  1362.242371  2497.546428
JAL      26.462468  34.150000  29.930000  28.319521  2039.601365  3261.681925
MICH     14.648660  19.778333  23.001667  23.051116  1142.041314  1991.420256
MOR      17.352254  24.585000  25.168333  22.958009  1783.159328  3021.130603
NAY      17.949447  22.538333  19.108333  20.902204  2180.600377  3434.493111
NL       24.470076  27.466667  25.881667  22.949583  2940.910871  3848.347547
OAX      11.260839  15.930000  19.013333  18.792112  1081.883854  2178.814959
PUE      18.312212  23.805000  25.116667  24.049993  1234.123198  2142.564515
QRO      15.741319  18.056667  20.711667  21.047433  1654.674121  2645.006925
QROO     19.277896  25.500000  26.688333  26.371584  2351.199020  3398.254878
SIN      15.350099  20.740000  20.795000  19.620582  2201.606341  3358.759737
SLP      15.411619  20.826667  18.535000  18.996134  1498.471952  2632.320807
SON      18.241839  21.181667  19.250000  26.703879  2663.393541  3928.377143
TAB       8.771752  24.306667  14.088333   9.823458  1952.883922  4906.926467
TAMPS    13.878581  15.276667  13.021667  16.611245  2404.372841  3730.689177
TLAX     15.775308  24.515000  24.881667  26.661088  1391.276494  2658.872717
VER      11.371096  14.658333  12.891667  14.505107  1611.501785  2750.235847
YUC      19.037963  20.328333  20.891667  22.590562  2481.914609  3787.211800
ZAC      14.157713  18.115000  19.913333  22.546900  1387.131651  2636.658215

                                          PIB                                \
sexenio            S3            S4        S1        S2        S3        S4
Estado
AGS       4759.803895   5412.439875  2.324281  2.789532  3.107504  2.926802
BC        4457.516010   5002.006502  1.986242  1.994136  2.688427  2.869279
BCS       6527.552174   6532.998440  3.717616  3.438257  3.184200  3.285400
CAMP      6528.398108   6154.105895  1.768191  1.106372  0.606164  0.999517
CDMX     11671.450757  11537.008951  2.882883  3.177194  3.584998  3.174802
CHIH      4584.625321   4831.727734  1.890807  2.498592  3.145820  2.886581
CHIS      3085.933565   3469.142892  3.031357  3.744797  4.825630  5.478919
COAH      4302.953735   4980.963734  2.295880  2.337123  2.095955  2.149707
COL       5337.516569   5697.959398  3.222271  3.706174  3.663271  3.624347
DGO       4390.585060   4812.446488  2.925125  3.669363  3.749677  3.647429
EDOMEX    3231.687512   4237.014192  1.667899  2.460442  3.536756  4.210475
GRO       3368.313927   4017.348218  2.800624  3.713869  4.802649  5.289586
GTO       3501.589468   3958.383033  2.144895  2.639267  3.214914  2.943858
HGO       3382.223091   3900.649711  2.784157  3.520055  3.714123  3.751012
JAL       4010.517066   4369.863288  2.370671  2.631433  2.769192  2.637943
MICH      2997.265011   3654.832726  2.374804  2.960606  3.433498  3.616189
MOR       4015.235864   4421.657411  2.404055  2.877130  3.596913  3.852864
NAY       4395.675251   4631.962669  4.250572  4.174055  4.274195  4.237984
NL        4410.500188   4787.235610  1.929468  1.789236  1.678128  1.720880
OAX       3442.090132   3906.549440  2.996017  3.913718  4.872722  5.259814
PUE       2986.473706   3560.968017  2.038187  2.686676  3.170985  3.453297
QRO       3472.558535   3961.063420  1.692619  1.924511  1.905851  1.864727
QROO      4325.838781   4555.082000  1.787965  2.008926  2.412636  2.460794
SIN       4219.919116   4530.052891  3.223983  3.388729  3.290561  3.241334
SLP       3551.426085   3976.568234  2.366658  2.816751  2.866942  2.781509
SON       4697.134939   6556.462809  2.488039  2.630418  2.432708  3.016672
TAB       5579.887034   5456.401394  3.476820  3.862720  2.125723  2.420918
TAMPS     4577.135122   5309.974047  2.491457  2.602696  2.765336  3.270008
TLAX      3774.490418   4294.428004  3.002392  3.728395  4.572246  4.999878
VER       3864.149372   4221.741225  3.104332  3.548097  3.562948  3.687558
YUC       4869.848031   5901.180611  3.692487  3.906389  4.182986  4.585732
ZAC       3777.198655   4428.986843  2.970269  3.820361  3.532769  3.810663

               PIBmxn
sexenio            S1            S2            S3            S4
Estado
AGS      9.891537e+07  1.411131e+08  1.816363e+08  2.412894e+08
BC       2.891727e+08  4.575103e+08  5.312925e+08  6.147987e+08
BCS      4.618982e+07  8.465654e+07  1.310734e+08  1.538414e+08
CAMP     1.032599e+08  5.618543e+08  9.070858e+08  6.012698e+08
CDMX     1.910708e+09  2.502050e+09  2.909223e+09  3.225673e+09
CHIH     3.686214e+08  4.449229e+08  5.106309e+08  6.269122e+08
CHIS     1.436119e+08  2.363310e+08  3.110425e+08  3.325513e+08
COAH     2.846366e+08  4.284907e+08  5.699384e+08  6.876700e+08
COL      4.600452e+07  7.021870e+07  9.503823e+07  1.139597e+08
DGO      1.089466e+08  1.552013e+08  1.942340e+08  2.330442e+08
EDOMEX   8.682037e+08  1.139658e+09  1.411700e+09  1.699874e+09
GRO      1.448980e+08  2.031436e+08  2.402757e+08  2.711524e+08
GTO      2.962322e+08  4.569626e+08  6.026181e+08  7.875265e+08
HGO      1.144994e+08  1.787695e+08  2.435231e+08  3.003898e+08
JAL      5.447565e+08  8.516092e+08  1.069852e+09  1.319316e+09
MICH     1.983033e+08  2.869981e+08  3.838592e+08  4.666389e+08
MOR      1.145929e+08  1.743667e+08  1.999899e+08  2.208556e+08
NAY      4.706279e+07  8.316344e+07  1.127580e+08  1.342813e+08
NL       5.783445e+08  9.177194e+08  1.230705e+09  1.419459e+09
OAX      1.296125e+08  2.101790e+08  2.719681e+08  2.978698e+08
PUE      3.077110e+08  4.339415e+08  5.496067e+08  6.395066e+08
QRO      1.446453e+08  2.308389e+08  3.338568e+08  4.277697e+08
QROO     1.109492e+08  1.821716e+08  2.394609e+08  2.930452e+08
SIN      1.681313e+08  2.680816e+08  3.633858e+08  4.194025e+08
SLP      1.484149e+08  2.342400e+08  3.222269e+08  3.964621e+08
SON      2.330521e+08  3.735370e+08  5.202322e+08  6.406597e+08
TAB      1.049072e+08  3.020806e+08  5.968304e+08  5.471797e+08
TAMPS    2.550199e+08  4.407199e+08  5.507243e+08  5.755020e+08
TLAX     4.443095e+07  7.775705e+07  9.712125e+07  1.100075e+08
VER      3.695373e+08  5.901964e+08  8.344656e+08  9.209298e+08
YUC      1.115263e+08  1.763347e+08  2.290040e+08  2.734291e+08
ZAC      6.626179e+07  1.006234e+08  1.611231e+08  1.833978e+08

In [499]:
meanSexenios = pd.DataFrame(gastoSexenios.groupby("Estado")["PIB"].mean())
meanSexenios = meanSexenios.sort_values(by="PIB",ascending=True)
meanSexenios["Orden"]=meanSexenios.reset_index().index+1
meanSexenios=pd.merge(meanSexenios,gastoIES,on="Estado",how="inner").sort_values(by=["Orden","Anio"],ascending=True)
meanSexenios.rename(columns={"PIB_x":"PIB","PIB_y":"PIB_mean"},inplace=True)
meanSexenios

,PIB,Orden,Anio,sexenio,EstadoPrint,PIB_mean,PIBmxn,GPT,PERCAPITA
Estado,,,,,,,,,
CAMP,1.125302,1,1995,S1,Campeche,1.537610,9.870427e+07,6.582009,2409.419805
CAMP,1.125302,1,1996,S1,Campeche,1.409711,9.974501e+07,4.817801,2180.641158
CAMP,1.125302,1,1997,S1,Campeche,1.591786,1.025906e+08,5.386548,2476.466433
CAMP,1.125302,1,1998,S1,Campeche,1.955212,9.328499e+07,4.810215,2707.429223
CAMP,1.125302,1,1999,S1,Campeche,2.076391,1.061146e+08,7.514958,3205.240990
...,...,...,...,...,...,...,...,...,...
NAY,4.234037,32,2013,S4,Nayarit,4.652251,1.195352e+08,21.766850,4719.165012
NAY,4.234037,32,2014,S4,Nayarit,4.195087,1.245053e+08,18.986366,4348.233386
NAY,4.234037,32,2015,S4,Nayarit,4.287882,1.340607e+08,19.823885,4697.155252
NAY,4.234037,32,2016,S4,Nayarit,3.981486,1.427993e+08,20.340046,4562.289993
NAY,4.234037,32,2017,S4,Nayarit,4.073215,1.505059e+08,23.593870,4832.969703

In [500]:
with pd.ExcelWriter("GASTO_CSV.xlsx") as writer:
  gastoSexenios.to_excel(writer, sheet_name="gasto_Sexenios")

In [501]:
gastoIES[["PIB","Anio"]]

             PIB  Anio
Estado
AGS     2.278928  1995
BC      2.163063  1995
BCS     3.742114  1995
CAMP    1.537610  1995
COAH    2.400249  1995
...          ...   ...
TAMPS   3.181874  2017
TLAX    4.977256  2017
VER     3.916907  2017
YUC     4.249854  2017
ZAC     3.747525  2017

[736 rows x 2 columns]

In [502]:
gastoIES

,Anio,sexenio,EstadoPrint,PIB,PIBmxn,GPT,PERCAPITA
Estado,,,,,,,
AGS,1995,S1,Aguascalientes,2.278928,7.917746e+07,10.647619,1959.069682
BC,1995,S1,Baja California,2.163063,2.294365e+08,22.601979,2317.759096
BCS,1995,S1,Baja California Sur,3.742114,3.864674e+07,21.956918,3609.493866
CAMP,1995,S1,Campeche,1.537610,9.870427e+07,6.582009,2409.419805
COAH,1995,S1,Coahuila,2.400249,2.400484e+08,17.083340,2621.670253
...,...,...,...,...,...,...,...
TAMPS,2017,S4,Tamaulipas,3.181874,6.078901e+08,18.173028,5339.333865
TLAX,2017,S4,Tlaxcala,4.977256,1.154003e+08,28.274960,4374.314206
VER,2017,S4,Veracruz,3.916907,9.402165e+08,17.513495,4510.971605
YUC,2017,S4,Yucatán,4.249854,3.004113e+08,22.314929,5875.742148
ZAC,2017,S4,Zacatecas,3.747525,1.971711e+08,25.655200,4616.959496

In [503]:
gastoPERC = pd.DataFrame(gastoIES.groupby("Estado")["PERCAPITA"].mean())
gastoPERC = gastoPERC.sort_values(by="PERCAPITA",ascending=True)
gastoPERC["OrdenPERC"]=gastoPERC.reset_index().index+1
gastoPERC=pd.merge(gastoIES,gastoPERC,on="Estado",how="inner").sort_values(by=["OrdenPERC","Anio"],ascending=True)
gastoPERC.rename(columns={"PERCAPITA_x":"PERCAPITA","PERCAPITA_y":"PERCAPITA_mean"},inplace=True)
gastoPERC=gastoPERC.sort_values(by=["Estado","Anio"],ascending=True)
gastoPERC

,Anio,sexenio,EstadoPrint,PIB,PIBmxn,GPT,PERCAPITA,PERCAPITA_mean,OrdenPERC
Estado,,,,,,,,,
AGS,1995,S1,Aguascalientes,2.278928,7.917746e+07,10.647619,1959.069682,4000.691352,25
AGS,1996,S1,Aguascalientes,1.987116,8.690798e+07,10.914541,1838.158261,4000.691352,25
AGS,1997,S1,Aguascalientes,2.143517,9.629624e+07,13.529886,2155.873869,4000.691352,25
AGS,1998,S1,Aguascalientes,2.319555,1.003836e+08,13.109835,2388.303511,4000.691352,25
AGS,1999,S1,Aguascalientes,2.761372,1.073634e+08,15.017065,2989.039477,4000.691352,25
...,...,...,...,...,...,...,...,...,...
ZAC,2013,S4,Zacatecas,3.941298,1.694030e+08,21.766645,4307.035375,2997.863710,12
ZAC,2014,S4,Zacatecas,3.834181,1.743785e+08,21.374967,4276.775771,2997.863710,12
ZAC,2015,S4,Zacatecas,3.856125,1.841990e+08,22.107488,4506.750129,2997.863710,12
ZAC,2016,S4,Zacatecas,3.674188,1.918374e+08,21.830197,4437.413443,2997.863710,12
ZAC,2017,S4,Zacatecas,3.747525,1.971711e+08,25.655200,4616.959496,2997.863710,12

In [504]:
gastoPIBmxn = pd.DataFrame(gastoIES.groupby("Estado")["PIBmxn"].mean())
gastoPIBmxn = gastoPIBmxn.sort_values(by="PIBmxn",ascending=True)
gastoPIBmxn["OrdenPIBmxn"]=gastoPIBmxn.reset_index().index+1
gastoPIBmxn["OrdenEndpoint"]=gastoPIBmxn.reset_index().index+1
gastoPIBmxn=pd.merge(gastoIES,gastoPIBmxn,on="Estado",how="inner").sort_values(by=["OrdenPIBmxn","Anio"],ascending=True)
gastoPIBmxn.rename(columns={"PIBmxn_x":"PIBmxn","PIBmxn_y":"PIBmxn_mean"},inplace=True)
gastoPIBmxn=gastoPIBmxn.sort_values(by=["OrdenPIBmxn","Estado","Anio"],ascending=True)
gastoPIBmxn

,Anio,sexenio,EstadoPrint,PIB,PIBmxn,GPT,PERCAPITA,PIBmxn_mean,OrdenPIBmxn,OrdenEndpoint
Estado,,,,,,,,,,
COL,1995,S1,Colima,3.120261,3.762578e+07,10.549447,2269.261021,7.988552e+07,1,1
COL,1996,S1,Colima,2.684352,4.093702e+07,9.105518,2093.342310,7.988552e+07,1,1
COL,1997,S1,Colima,3.053185,4.408892e+07,9.377045,2530.460465,7.988552e+07,1,1
COL,1998,S1,Colima,3.227215,4.715884e+07,10.881608,2825.900874,7.988552e+07,1,1
COL,1999,S1,Colima,3.576777,5.171873e+07,13.254989,3399.547342,7.988552e+07,1,1
...,...,...,...,...,...,...,...,...,...,...
CDMX,2013,S4,Ciudad de México,3.737296,3.083407e+09,8.521787,12956.978154,2.611315e+09,32,32
CDMX,2014,S4,Ciudad de México,3.022471,3.093859e+09,6.671049,10536.780110,2.611315e+09,32,32
CDMX,2015,S4,Ciudad de México,3.190114,3.200794e+09,6.742936,11531.744309,2.611315e+09,32,32
CDMX,2016,S4,Ciudad de México,3.016004,3.341291e+09,5.826136,11408.210662,2.611315e+09,32,32
CDMX,2017,S4,Ciudad de México,2.908126,3.409016e+09,6.810649,11251.331521,2.611315e+09,32,32

In [505]:
gastoPIBmxn["ORPIBmxn"]=gastoPIBmxn.OrdenPIBmxn
gastoPIBmxn

,Anio,sexenio,EstadoPrint,PIB,PIBmxn,GPT,PERCAPITA,PIBmxn_mean,OrdenPIBmxn,OrdenEndpoint,ORPIBmxn
Estado,,,,,,,,,,,
COL,1995,S1,Colima,3.120261,3.762578e+07,10.549447,2269.261021,7.988552e+07,1,1,1
COL,1996,S1,Colima,2.684352,4.093702e+07,9.105518,2093.342310,7.988552e+07,1,1,1
COL,1997,S1,Colima,3.053185,4.408892e+07,9.377045,2530.460465,7.988552e+07,1,1,1
COL,1998,S1,Colima,3.227215,4.715884e+07,10.881608,2825.900874,7.988552e+07,1,1,1
COL,1999,S1,Colima,3.576777,5.171873e+07,13.254989,3399.547342,7.988552e+07,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...
CDMX,2013,S4,Ciudad de México,3.737296,3.083407e+09,8.521787,12956.978154,2.611315e+09,32,32,32
CDMX,2014,S4,Ciudad de México,3.022471,3.093859e+09,6.671049,10536.780110,2.611315e+09,32,32,32
CDMX,2015,S4,Ciudad de México,3.190114,3.200794e+09,6.742936,11531.744309,2.611315e+09,32,32,32
CDMX,2016,S4,Ciudad de México,3.016004,3.341291e+09,5.826136,11408.210662,2.611315e+09,32,32,32
CDMX,2017,S4,Ciudad de México,2.908126,3.409016e+09,6.810649,11251.331521,2.611315e+09,32,32,32

In [506]:
gastoPIBmxn.to_json(r"datos/JSON_PIBmxn.json",orient="table")

In [507]:
gastoPERC = pd.DataFrame(gastoIES.groupby("Estado")["PERCAPITA"].mean())
gastoPERC = gastoPERC.sort_values(by="PERCAPITA",ascending=True)
gastoPERC["OrdenPERC"]=gastoPERC.reset_index().index+1
gastoPERC["OrdenEndpoint"]=gastoPERC.reset_index().index+1
gastoPERC=pd.merge(gastoIES,gastoPERC,on="Estado",how="inner").sort_values(by=["OrdenPERC","Anio"],ascending=True)
gastoPERC.rename(columns={"PERCAPITA_x":"PERCAPITA","PERCAPITA_y":"PERCAPITA_mean"},inplace=True)
gastoPERC=gastoPERC.sort_values(by=["OrdenPERC","Estado","Anio"],ascending=True)
gastoPERC

,Anio,sexenio,EstadoPrint,PIB,PIBmxn,GPT,PERCAPITA,PERCAPITA_mean,OrdenPERC,OrdenEndpoint
Estado,,,,,,,,,,
CHIS,1995,S1,Chiapas,3.082612,1.282853e+08,12.542548,1059.624317,2355.212141,1,1
CHIS,1996,S1,Chiapas,2.782510,1.327687e+08,8.104573,967.161306,2355.212141,1,1
CHIS,1997,S1,Chiapas,2.395682,1.432514e+08,6.903133,878.316264,2355.212141,1,1
CHIS,1998,S1,Chiapas,2.675156,1.452491e+08,8.131984,972.790184,2355.212141,1,1
CHIS,1999,S1,Chiapas,3.553554,1.497202e+08,10.620692,1302.927966,2355.212141,1,1
...,...,...,...,...,...,...,...,...,...,...
CDMX,2013,S4,Ciudad de México,3.737296,3.083407e+09,8.521787,12956.978154,9498.226880,32,32
CDMX,2014,S4,Ciudad de México,3.022471,3.093859e+09,6.671049,10536.780110,9498.226880,32,32
CDMX,2015,S4,Ciudad de México,3.190114,3.200794e+09,6.742936,11531.744309,9498.226880,32,32
CDMX,2016,S4,Ciudad de México,3.016004,3.341291e+09,5.826136,11408.210662,9498.226880,32,32
CDMX,2017,S4,Ciudad de México,2.908126,3.409016e+09,6.810649,11251.331521,9498.226880,32,32

In [508]:
gastoPERC["ORPERC"]=gastoPERC.OrdenPERC
gastoPERC

,Anio,sexenio,EstadoPrint,PIB,PIBmxn,GPT,PERCAPITA,PERCAPITA_mean,OrdenPERC,OrdenEndpoint,ORPERC
Estado,,,,,,,,,,,
CHIS,1995,S1,Chiapas,3.082612,1.282853e+08,12.542548,1059.624317,2355.212141,1,1,1
CHIS,1996,S1,Chiapas,2.782510,1.327687e+08,8.104573,967.161306,2355.212141,1,1,1
CHIS,1997,S1,Chiapas,2.395682,1.432514e+08,6.903133,878.316264,2355.212141,1,1,1
CHIS,1998,S1,Chiapas,2.675156,1.452491e+08,8.131984,972.790184,2355.212141,1,1,1
CHIS,1999,S1,Chiapas,3.553554,1.497202e+08,10.620692,1302.927966,2355.212141,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...
CDMX,2013,S4,Ciudad de México,3.737296,3.083407e+09,8.521787,12956.978154,9498.226880,32,32,32
CDMX,2014,S4,Ciudad de México,3.022471,3.093859e+09,6.671049,10536.780110,9498.226880,32,32,32
CDMX,2015,S4,Ciudad de México,3.190114,3.200794e+09,6.742936,11531.744309,9498.226880,32,32,32
CDMX,2016,S4,Ciudad de México,3.016004,3.341291e+09,5.826136,11408.210662,9498.226880,32,32,32
CDMX,2017,S4,Ciudad de México,2.908126,3.409016e+09,6.810649,11251.331521,9498.226880,32,32,32

In [509]:
gastoPERC.to_json(r"datos/JSON_PERC.json",orient="table")

In [510]:
gastoPIB = pd.DataFrame(gastoIES.groupby("Estado")["PIB"].mean())
gastoPIB = gastoPIB.sort_values(by="PIB",ascending=True)
gastoPIB["OrdenPIB"]=gastoPIB.reset_index().index+1
gastoPIB["OrdenEndpoint"]=gastoPIB.reset_index().index+1
gastoPIB=pd.merge(gastoIES,gastoPIB,on="Estado",how="inner").sort_values(by=["OrdenPIB","Anio"],ascending=True)
gastoPIB.rename(columns={"PIB_x":"PIB","PIB_y":"PIB_mean"},inplace=True)
gastoPIB

,Anio,sexenio,EstadoPrint,PIB,PIBmxn,GPT,PERCAPITA,PIB_mean,OrdenPIB,OrdenEndpoint
Estado,,,,,,,,,,
CAMP,1995,S1,Campeche,1.537610,9.870427e+07,6.582009,2409.419805,1.125302,1,1
CAMP,1996,S1,Campeche,1.409711,9.974501e+07,4.817801,2180.641158,1.125302,1,1
CAMP,1997,S1,Campeche,1.591786,1.025906e+08,5.386548,2476.466433,1.125302,1,1
CAMP,1998,S1,Campeche,1.955212,9.328499e+07,4.810215,2707.429223,1.125302,1,1
CAMP,1999,S1,Campeche,2.076391,1.061146e+08,7.514958,3205.240990,1.125302,1,1
...,...,...,...,...,...,...,...,...,...,...
NAY,2013,S4,Nayarit,4.652251,1.195352e+08,21.766850,4719.165012,4.234037,32,32
NAY,2014,S4,Nayarit,4.195087,1.245053e+08,18.986366,4348.233386,4.234037,32,32
NAY,2015,S4,Nayarit,4.287882,1.340607e+08,19.823885,4697.155252,4.234037,32,32
NAY,2016,S4,Nayarit,3.981486,1.427993e+08,20.340046,4562.289993,4.234037,32,32
NAY,2017,S4,Nayarit,4.073215,1.505059e+08,23.593870,4832.969703,4.234037,32,32

In [511]:
gastoPIB.to_json(r"datos/JSON_PIB.json",orient="table")

In [512]:
gastoGPT = pd.DataFrame(gastoIES.groupby("Estado")["GPT"].mean())
gastoGPT = gastoGPT.sort_values(by="GPT",ascending=True)
gastoGPT["OrdenGPT"]=gastoGPT.reset_index().index+1
gastoGPT["OrdenEndpoint"]=gastoGPT.reset_index().index+1
gastoGPT=pd.merge(gastoIES,gastoGPT,on="Estado",how="inner").sort_values(by=["OrdenGPT","Anio"],ascending=True)
gastoGPT.rename(columns={"GPT_x":"GPT","GPT_y":"GPT_mean"},inplace=True)
gastoGPT

,Anio,sexenio,EstadoPrint,PIB,PIBmxn,GPT,PERCAPITA,GPT_mean,OrdenGPT,OrdenEndpoint
Estado,,,,,,,,,,
CAMP,1995,S1,Campeche,1.537610,9.870427e+07,6.582009,2409.419805,5.664379,1,1
CAMP,1996,S1,Campeche,1.409711,9.974501e+07,4.817801,2180.641158,5.664379,1,1
CAMP,1997,S1,Campeche,1.591786,1.025906e+08,5.386548,2476.466433,5.664379,1,1
CAMP,1998,S1,Campeche,1.955212,9.328499e+07,4.810215,2707.429223,5.664379,1,1
CAMP,1999,S1,Campeche,2.076391,1.061146e+08,7.514958,3205.240990,5.664379,1,1
...,...,...,...,...,...,...,...,...,...,...
JAL,2013,S4,Jalisco,2.774804,1.174940e+09,30.261226,4210.927569,29.776192,32,32
JAL,2014,S4,Jalisco,2.786809,1.226708e+09,29.407469,4361.567434,29.776192,32,32
JAL,2015,S4,Jalisco,2.673096,1.313154e+09,27.847115,4425.757595,29.776192,32,32
JAL,2016,S4,Jalisco,2.459699,1.415365e+09,26.469881,4339.681327,29.776192,32,32
JAL,2017,S4,Jalisco,2.495307,1.466416e+09,27.611914,4511.382516,29.776192,32,32

In [513]:
gastoGPT.to_json(r"datos/JSON_GPT.json",orient="table")

In [514]:
gastoALF = pd.DataFrame(gastoIES.groupby("Estado")["GPT"].mean())
gastoALF = gastoALF.sort_values(by="Estado",ascending=True)
gastoALF["Orden"]=gastoALF.reset_index().index+1
gastoALF=pd.merge(gastoIES,gastoALF,on="Estado",how="inner").sort_values(by=["Estado","Anio"],ascending=True)
gastoALF.rename(columns={"GPT_x":"GPT","GPT_y":"GPT_mean"},inplace=True)
gastoALF

,Anio,sexenio,EstadoPrint,PIB,PIBmxn,GPT,PERCAPITA,GPT_mean,Orden
Estado,,,,,,,,,
AGS,1995,S1,Aguascalientes,2.278928,7.917746e+07,10.647619,1959.069682,20.082444,1
AGS,1996,S1,Aguascalientes,1.987116,8.690798e+07,10.914541,1838.158261,20.082444,1
AGS,1997,S1,Aguascalientes,2.143517,9.629624e+07,13.529886,2155.873869,20.082444,1
AGS,1998,S1,Aguascalientes,2.319555,1.003836e+08,13.109835,2388.303511,20.082444,1
AGS,1999,S1,Aguascalientes,2.761372,1.073634e+08,15.017065,2989.039477,20.082444,1
...,...,...,...,...,...,...,...,...,...
ZAC,2013,S4,Zacatecas,3.941298,1.694030e+08,21.766645,4307.035375,18.515251,32
ZAC,2014,S4,Zacatecas,3.834181,1.743785e+08,21.374967,4276.775771,18.515251,32
ZAC,2015,S4,Zacatecas,3.856125,1.841990e+08,22.107488,4506.750129,18.515251,32
ZAC,2016,S4,Zacatecas,3.674188,1.918374e+08,21.830197,4437.413443,18.515251,32
ZAC,2017,S4,Zacatecas,3.747525,1.971711e+08,25.655200,4616.959496,18.515251,32

In [515]:
gastoALF.to_json(r"datos/JSON_ALF.json",orient="table")

In [516]:
with pd.ExcelWriter("GASTO_CSV.xlsx") as writer:
  gastoPERC.to_excel(writer, sheet_name="PERC")
  gastoPIB.to_excel(writer, sheet_name="PIB")
  gastoGPT.to_excel(writer, sheet_name="GPT")
  gastoALF.to_excel(writer, sheet_name="ALF")

In [517]:
gastoIES

,Anio,sexenio,EstadoPrint,PIB,PIBmxn,GPT,PERCAPITA
Estado,,,,,,,
AGS,1995,S1,Aguascalientes,2.278928,7.917746e+07,10.647619,1959.069682
BC,1995,S1,Baja California,2.163063,2.294365e+08,22.601979,2317.759096
BCS,1995,S1,Baja California Sur,3.742114,3.864674e+07,21.956918,3609.493866
CAMP,1995,S1,Campeche,1.537610,9.870427e+07,6.582009,2409.419805
COAH,1995,S1,Coahuila,2.400249,2.400484e+08,17.083340,2621.670253
...,...,...,...,...,...,...,...
TAMPS,2017,S4,Tamaulipas,3.181874,6.078901e+08,18.173028,5339.333865
TLAX,2017,S4,Tlaxcala,4.977256,1.154003e+08,28.274960,4374.314206
VER,2017,S4,Veracruz,3.916907,9.402165e+08,17.513495,4510.971605
YUC,2017,S4,Yucatán,4.249854,3.004113e+08,22.314929,5875.742148
ZAC,2017,S4,Zacatecas,3.747525,1.971711e+08,25.655200,4616.959496

In [518]:
presis = [
    "Ernesto Zedillo Ponce de León", 
    "Vicente Fox Quesada", 
    "Felipe Calderón Hinojosa",
    "Enrique Peña Nieto"]

presidenteCol = pd.cut(gastoIES.Anio, bins=sexenios, precision=0, right=False, labels=presis)
gastoIES.insert(1, "presidente", presidenteCol)
gastoIES.head()

,Anio,presidente,sexenio,EstadoPrint,PIB,PIBmxn,GPT,PERCAPITA
Estado,,,,,,,,
AGS,1995,Ernesto Zedillo Ponce de León,S1,Aguascalientes,2.278928,7.917746e+07,10.647619,1959.069682
BC,1995,Ernesto Zedillo Ponce de León,S1,Baja California,2.163063,2.294365e+08,22.601979,2317.759096
BCS,1995,Ernesto Zedillo Ponce de León,S1,Baja California Sur,3.742114,3.864674e+07,21.956918,3609.493866
CAMP,1995,Ernesto Zedillo Ponce de León,S1,Campeche,1.537610,9.870427e+07,6.582009,2409.419805
COAH,1995,Ernesto Zedillo Ponce de León,S1,Coahuila,2.400249,2.400484e+08,17.083340,2621.670253

In [519]:
gastoIES.sexenio.unique()

['S1', 'S2', 'S3', 'S4']
Categories (4, object): ['S1' < 'S2' < 'S3' < 'S4']

In [520]:
gastoIES=gastoIES.groupby(["Estado", "sexenio"]).mean()

In [521]:
meanPERC = pd.DataFrame(gastoIES.groupby("Estado")["PERCAPITA"].mean())
meanPERC = meanPERC.sort_values(by="PERCAPITA",ascending=True)
meanPERC["Orden"]=meanPERC.reset_index().index+1
meanPERC=pd.merge(meanPERC,gastoIES,on="Estado",how="inner").sort_values(by=["Orden","Anio"],ascending=True)
meanPERC.rename(columns={"PERCAPITA_x":"PERCAPITA","PERCAPITA_y":"PERCAPITA_mean"},inplace=True)
meanPERC

,PERCAPITA,Orden,Anio,PIB,PIBmxn,GPT,PERCAPITA_mean
Estado,,,,,,,
CHIS,2401.625922,1,1997.5,3.031357,1.436119e+08,9.543822,1103.833708
CHIS,2401.625922,1,2003.5,3.744797,2.363310e+08,15.070000,1947.593523
CHIS,2401.625922,1,2009.5,4.825630,3.110425e+08,17.701667,3085.933565
CHIS,2401.625922,1,2015.0,5.478919,3.325513e+08,18.481366,3469.142892
MICH,2446.389827,2,1997.5,2.374804,1.983033e+08,14.648660,1142.041314
...,...,...,...,...,...,...,...
BCS,5607.353616,31,2015.0,3.285400,1.538414e+08,17.387763,6532.998440
CDMX,9583.176133,32,1997.5,2.882883,1.910708e+09,13.131239,6268.273877
CDMX,9583.176133,32,2003.5,3.177194,2.502050e+09,10.718333,8855.970946
CDMX,9583.176133,32,2009.5,3.584998,2.909223e+09,9.536667,11671.450757
CDMX,9583.176133,32,2015.0,3.174802,3.225673e+09,6.914511,11537.008951

In [522]:
meanPERC.to_json(r"datos/JSON_meanPERC.json",orient="table")

In [523]:
with pd.ExcelWriter("GASTO_CSV.xlsx") as writer:
  gastoIES.to_excel(writer, sheet_name="IES")
  gastoPERC.to_excel(writer, sheet_name="PERC")
  gastoPIB.to_excel(writer, sheet_name="PIB")
  gastoGPT.to_excel(writer, sheet_name="GPT")
  gastoALF.to_excel(writer, sheet_name="ALF")
  meanPERC.to_excel(writer, sheet_name="meanPERC")

In [524]:
meanPIBmxn = pd.DataFrame(gastoIES.groupby("Estado")["PIBmxn"].mean())
meanPIBmxn = meanPIBmxn.sort_values(by="PIBmxn",ascending=True)
meanPIBmxn["Orden"]=meanPIBmxn.reset_index().index+1
meanPIBmxn=pd.merge(meanPIBmxn,gastoIES,on="Estado",how="inner").sort_values(by=["Orden","Anio"],ascending=True)
meanPIBmxn.rename(columns={"PIBmxn_x":"PIBmxn","PIBmxn_y":"PIBmxn_mean"},inplace=True)
meanPIBmxn

,PIBmxn,Orden,Anio,PIB,PIBmxn_mean,GPT,PERCAPITA
Estado,,,,,,,
COL,8.130528e+07,1,1997.5,3.222271,4.600452e+07,10.633101,2792.484812
COL,8.130528e+07,1,2003.5,3.706174,7.021870e+07,13.263333,4476.852641
COL,8.130528e+07,1,2009.5,3.663271,9.503823e+07,11.938333,5337.516569
COL,8.130528e+07,1,2015.0,3.624347,1.139597e+08,11.692702,5697.959398
TLAX,8.232919e+07,2,1997.5,3.002392,4.443095e+07,15.775308,1391.276494
...,...,...,...,...,...,...,...
EDOMEX,1.279859e+09,31,2015.0,4.210475,1.699874e+09,30.597387,4237.014192
CDMX,2.636914e+09,32,1997.5,2.882883,1.910708e+09,13.131239,6268.273877
CDMX,2.636914e+09,32,2003.5,3.177194,2.502050e+09,10.718333,8855.970946
CDMX,2.636914e+09,32,2009.5,3.584998,2.909223e+09,9.536667,11671.450757
CDMX,2.636914e+09,32,2015.0,3.174802,3.225673e+09,6.914511,11537.008951

In [525]:
meanPIBmxn.to_json(r"datos/JSON_meanPIBmxn.json",orient="table")

In [526]:
meanPIB = pd.DataFrame(gastoIES.groupby("Estado")["PIB"].mean())
meanPIB = meanPIB.sort_values(by="PIB",ascending=True)
meanPIB["Orden"]=meanPIB.reset_index().index+1
meanPIB=pd.merge(meanPIB,gastoIES,on="Estado",how="inner").sort_values(by=["Orden","Anio"],ascending=True)
meanPIB.rename(columns={"PIB_x":"PIB","PIB_y":"PIB_mean"},inplace=True)
meanPIB

,PIB,Orden,Anio,PIB_mean,PIBmxn,GPT,PERCAPITA
Estado,,,,,,,
CAMP,1.120061,1,1997.5,1.768191,1.032599e+08,6.018588,2740.754515
CAMP,1.120061,1,2003.5,1.106372,5.618543e+08,7.696667,4751.925666
CAMP,1.120061,1,2009.5,0.606164,9.070858e+08,5.236667,6528.398108
CAMP,1.120061,1,2015.0,0.999517,6.012698e+08,3.313836,6154.105895
NL,1.779428,2,1997.5,1.929468,5.783445e+08,24.470076,2940.910871
...,...,...,...,...,...,...,...
OAX,4.260568,31,2015.0,5.259814,2.978698e+08,18.792112,3906.549440
CHIS,4.270176,32,1997.5,3.031357,1.436119e+08,9.543822,1103.833708
CHIS,4.270176,32,2003.5,3.744797,2.363310e+08,15.070000,1947.593523
CHIS,4.270176,32,2009.5,4.825630,3.110425e+08,17.701667,3085.933565
CHIS,4.270176,32,2015.0,5.478919,3.325513e+08,18.481366,3469.142892

In [527]:
meanPIB.to_json(r"datos/JSON_meanPIB.json",orient="table")

In [528]:
with pd.ExcelWriter("GASTO_CSV.xlsx") as writer:
  gastoPERC.to_excel(writer, sheet_name="PERC")
  gastoPIB.to_excel(writer, sheet_name="PIB")
  gastoGPT.to_excel(writer, sheet_name="GPT")
  gastoALF.to_excel(writer, sheet_name="ALF")
  meanPERC.to_excel(writer, sheet_name="meanPERC")
  meanPIB.to_excel(writer, sheet_name="meanPIB")

In [529]:
meanGPT = pd.DataFrame(gastoIES.groupby("Estado")["GPT"].mean())
meanGPT = meanGPT.sort_values(by="GPT",ascending=True)
meanGPT["Orden"]=meanGPT.reset_index().index+1
meanGPT=pd.merge(meanGPT,gastoIES,on="Estado",how="inner").sort_values(by=["Orden","Anio"],ascending=True)
meanGPT.rename(columns={"GPT_x":"GPT","GPT_y":"GPT_mean"},inplace=True)
meanGPT

,GPT,Orden,Anio,PIB,PIBmxn,GPT_mean,PERCAPITA
Estado,,,,,,,
CAMP,5.566440,1,1997.5,1.768191,1.032599e+08,6.018588,2740.754515
CAMP,5.566440,1,2003.5,1.106372,5.618543e+08,7.696667,4751.925666
CAMP,5.566440,1,2009.5,0.606164,9.070858e+08,5.236667,6528.398108
CAMP,5.566440,1,2015.0,0.999517,6.012698e+08,3.313836,6154.105895
CDMX,10.075187,2,1997.5,2.882883,1.910708e+09,13.131239,6268.273877
...,...,...,...,...,...,...,...
EDOMEX,28.010935,31,2015.0,4.210475,1.699874e+09,30.597387,4237.014192
JAL,29.715497,32,1997.5,2.370671,5.447565e+08,26.462468,2039.601365
JAL,29.715497,32,2003.5,2.631433,8.516092e+08,34.150000,3261.681925
JAL,29.715497,32,2009.5,2.769192,1.069852e+09,29.930000,4010.517066
JAL,29.715497,32,2015.0,2.637943,1.319316e+09,28.319521,4369.863288

In [530]:
meanGPT.to_json(r"datos/JSON_meanGPT.json",orient="table")

In [531]:
with pd.ExcelWriter("GASTO_CSV.xlsx") as writer:
  gastoPERC.to_excel(writer, sheet_name="PERC")
  gastoPIB.to_excel(writer, sheet_name="PIB")
  gastoGPT.to_excel(writer, sheet_name="GPT")
  gastoALF.to_excel(writer, sheet_name="ALF")
  meanPERC.to_excel(writer, sheet_name="meanPERC")
  meanPIB.to_excel(writer, sheet_name="meanPIB")
  meanGPT.to_excel(writer, sheet_name="meanGPT")